---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "frr_isis_basic_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/frr/isisd.conf
      copy:
        src: "{{ frr_isis_conf_file }}"
        dest: "{{ frr_isis_conf_file_bck }}"
        remote_src: true

    - name: Update hostname info in isisd.conf
      replace:
        path: "{{ frr_isis_conf_file }}"
        regexp: "^hostname isisd"
        replace: "hostname {{ inventory_hostname }}"


- hosts: leaf[0]:spine[1]
  become: true
  tasks:
    - name: Assign mtu to eth-21-1 interface
      command: "ifconfig eth-21-1 mtu 1500 up"

    - name: Configure isis for eth-21-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-21-1"
        marker: "! eth-21-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf[0]:spine[0]
  become: true
  tasks:
    - name: Assign mtu to eth-11-1 interface
      command: "ifconfig eth-11-1 mtu 1500 up"

    - name: Configure isis for eth-11-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-11-1"
        marker: "! eth-11-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf[1]:spine[1]
  become: true
  tasks:
    - name: Assign mtu to eth-5-1 interface
      command: "ifconfig eth-5-1 mtu 1500 up"

    - name: Configure isis for eth-5-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-5-1"
        marker: "! eth-5-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf[1]:spine[0]
  become: true
  tasks:
    - name: Assign mtu to eth-27-1 interface
      command: "ifconfig eth-27-1 mtu 1500 up"

    - name: Configure isis for eth-27-1
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        insertafter: "interface eth-27-1"
        marker: "! eth-27-1 {mark}"
        block: |
          ip router isis platina


- hosts: leaf:spine
  become: true
  tasks:
    - name: Add isis config in /etc/frr/isisd.conf
      blockinfile:
        path: "{{ frr_isis_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/isis_basic.conf') }}"
      
    - name: Restart frr
      service:
        name: frr
        state: restarted

    - name: Wait for few seconds for isis to establish connection
      pause:
        seconds: 35

    - file:
        path: "{{ isis_log_dir }}"
        state: directory

    - name: Verify frr isis basic
      test_isis_basic:
        switch_name: "{{ inventory_hostname }}"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "frr"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ isis_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - name: Revert mtu of interfaces to it's original
      command: "ifconfig eth-{{item}}-1 mtu 9216 up"
      with_items:
        - "11"
        - "21"
        - "5"
        - "27"

    - shell: "goes hget platina package | grep version:"
      register: version_out

    - shell: "goes hget platina package | grep tag:"
      register: tag_out

    - name: Store GOES version and tag details in redis db
      store_goes_details:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        version_details: "{{ version_out.stdout }}"
        tag_details: "{{ tag_out.stdout }}"
      delegate_to: 127.0.0.1

    - name: Restore backup of /etc/frr/isisd.conf
      copy:
        src: "{{ frr_isis_conf_file_bck }}"
        dest: "{{ frr_isis_conf_file }}"
        remote_src: true
        owner: root
        group: root
        mode: 0644

    - name: Remove backup file
      file:
        path: "{{ frr_isis_conf_file_bck }}"
        state: absent

    - service:
        name: frr
        state: restarted



- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"

#    - name: Get playbook run details
#      set_fact:
#        playbook_run: "{{ lookup('file', '{{ ansible_log_file_path }}') }}"
#
#    - name: Store the ansible execution log in redis hash
#      command: "redis-cli -p 9090 hset {{ hostvars['server_emulator']['hash_name'] }} 'result.playbook' '{{ playbook_run }}'"
#
#    - file:
#        path: "{{ ansible_log_file_path }}"
#        state: absent
