---

- hosts: leaf,spine
  become: true
  tasks:
    - name: Take backup of Quagga.conf
      copy:
        src: /etc/quagga/Quagga.conf
        dest: /etc/quagga/Quagga.conf.bck
        remote_src: true
        owner: root
        group: root
        mode: 0644


- hosts: leaf[0]
  become: true
  tasks:
    - name: Add bgp config in quagga.conf
      blockinfile:
        path: /etc/quagga/Quagga.conf
        insertafter: "interface lo"
        backup: yes
        marker: ""
        block: |
          !
          router bgp 65200
            bgp router-id 172.17.2.29
            neighbor 10.0.3.31 remote-as 65200
            neighbor 10.0.19.32 remote-as 65200

#    - name: Restart quagga
#      command: service quagga restart
#
#    - name: Verify bgp neighbors
#      command: "vtysh -c 'sh ip bgp neighbors'"
#      register: leaf0_out
   

- hosts: leaf[1]
  become: true
  tasks:
    - name: Add bgp config in quagga.conf
      blockinfile:
        path: /etc/quagga/Quagga.conf
        insertafter: "interface lo"
        backup: yes
        marker: ""
        block: |
          !
          router bgp 65200
            bgp router-id 172.17.2.30
            neighbor 10.0.3.32 remote-as 65200
            neighbor 10.0.19.31 remote-as 65200

    - name: Restart quagga
      command: service quagga restart

    - name: Verify bgp neighbors
      command: "vtysh -c 'sh ip bgp neighbors'"
      register: leaf1_out


- hosts: spine[0]
  become: true
  tasks:
    - name: Add bgp config in quagga.conf
      blockinfile:
        path: /etc/quagga/Quagga.conf
        insertafter: "interface lo"
        backup: yes
        marker: ""
        block: |
          !
          router bgp 65200
            bgp router-id 172.17.2.31
            neighbor 10.0.3.29 remote-as 65200
            neighbor 10.0.19.30 remote-as 65200

    - name: Restart quagga
      command: service quagga restart

    - name: Verify bgp neighbors
      command: "vtysh -c 'sh ip bgp neighbors'"
      register: spine0_out


- hosts: spine[1]
  become: true
  tasks:
    - name: Add bgp config in quagga.conf
      blockinfile:
        path: /etc/quagga/Quagga.conf
        insertafter: "interface lo"
        backup: yes
        marker: ""
        block: |
          !
          router bgp 65200
            bgp router-id 172.17.2.32
            neighbor 10.0.3.30 remote-as 65200
            neighbor 10.0.19.29 remote-as 65200

    - name: Restart quagga
      command: service quagga restart

    - name: Verify bgp neighbors
      command: "vtysh -c 'sh ip bgp neighbors'"
      register: spine0_out


- hosts: leaf,spine
  become: true
  tasks:
    - name: Restore backup of Quagga.conf 
      copy:
        src: /etc/quagga/Quagga.conf.bck
        dest: /etc/quagga/Quagga.conf
        remote_src: true
        owner: root
        group: root
        mode: 0644

    - name: Remove backup file
      file:
        path: /etc/quagga/Quagga.conf.bck
        state: absent

