---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "frr_ospf_hello_and_dead_timers_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file }}"
        dest: "{{ frr_ospf_conf_file_bck }}"
        remote_src: true

    - name: Configure hello and dead time interval for eth-7-1
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        insertafter: "interface eth-7-1"
        marker: "! {mark} foo"
        block: |
          ip ospf dead-interval 10
          ip ospf hello-interval 5

    - name: Configure hello and dead time interval for eth-17-1
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        insertafter: "interface eth-17-1"
        marker: "! {mark} bar"
        block: |
          ip ospf dead-interval 10
          ip ospf hello-interval 5

    - name: Add ospf config in /etc/frr/ospfd.conf
      blockinfile:
        path: "{{ frr_ospf_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_interval.conf') }}"

    - name: Restart frr service
      service:
        name: frr
        state: restarted

    - name: Wait for 35 secs for ospf to establish communication
      pause:
        seconds: 35

    - file:
        path: "{{ ospf_log_dir }}"
        state: directory

    - name: Verify frr ospf hello and dead time intervals
      test_ospf_intervals:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "7,17"
        hello_timer: "5"
        dead_timer: "10"
        package_name: "frr"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - name: Get goes version details
      shell: "goes hget platina package | grep version:"
      register: version_out

    - name: Get goes tag details
      shell: "goes hget platina package | grep tag:"
      register: tag_out

    - name: Store goes version and tag details in redis db
      store_goes_details:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        version_details: "{{ version_out.stdout }}"
        tag_details: "{{ tag_out.stdout }}"
      delegate_to: 127.0.0.1

    - name: Restore backup of /etc/frr/ospfd.conf
      copy:
        src: "{{ frr_ospf_conf_file_bck }}"
        dest: "{{ frr_ospf_conf_file }}"
        remote_src: true
        owner: root
        group: root
        mode: 0644

    - name: Remove backup file
      file:
        path: "{{ frr_ospf_conf_file_bck }}"
        state: absent


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"

#    - name: Get playbook run details
#      set_fact:
#        playbook_run: "{{ lookup('file', '{{ ansible_log_file_path }}') }}"
#
#    - name: Store the ansible execution log in redis hash
#      command: "redis-cli -p 9090 hset {{ hostvars['server_emulator']['hash_name'] }} 'result.playbook' '{{ playbook_run }}'"
#
#    - file:
#        path: "{{ ansible_log_file_path }}"
#        state: absent
