---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "quagga_ospf_ecmp_loadbalancing_basic_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file }}"
        dest: "{{ quagga_ospf_conf_file_bck }}"
        remote_src: true

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - name: Configure cost on eth-7-1
      blockinfile:
        path: "{{ quagga_ospf_conf_file }}"
        insertafter: "interface eth-7-1"
        marker: "! eth-7-1 {mark}"
        block: |
          ip ospf cost 10

    - name: Configure cost on eth-17-1
      blockinfile:
        path: "{{ quagga_ospf_conf_file }}"
        insertafter: "interface eth-17-1"
        marker: "! eth-17-1 {mark}"
        block: |
          ip ospf cost 10

    - name: Add ospf config in /etc/quagga/ospfd.conf
      blockinfile:
        path: "{{ quagga_ospf_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_loopback.conf') }}"

    - name: Restart quagga service
      service:
        name: quagga
        state: restarted

    - name: Wait few secs for ospf to establish communication
      pause:
        seconds: 35

    - file:
        path: "{{ ospf_log_dir }}"
        state: directory

    - name: Verify quagga ecmp load balancing basic
      test_ospf_ecmp_basic:
        switch_name: "{{ inventory_hostname }}"
        eth_list: "7,17"
        cost: "10"
        config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_loopback.conf') }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - include: ../../playbooks/get_goes_version_and_tags.yml

    - name: Restore backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file_bck }}"
        dest: "{{ quagga_ospf_conf_file }}"
        remote_src: true

    - name: Remove backup file
      file:
        path: "{{ quagga_ospf_conf_file_bck }}"
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - name: Restart quagga
      service:
        name: quagga
        state: restarted


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"
