---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "quagga_ospf_loadbalancing_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/network/interfaces file
      copy:
        src: /etc/network/interfaces
        dest: /etc/network/interfaces.bck
        remote_src: true

    - name: Take backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file }}"
        dest: "{{ quagga_ospf_conf_file_bck }}"
        remote_src: true

    - name: Add ospf config in /etc/quagga/ospfd.conf
      blockinfile:
        path: "{{ quagga_ospf_conf_file }}"
        marker: ""
        block: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_loadbalancing.conf') }}"

    - name: Add dummy interface
      add_dummy_interface:
        switch_name: "{{ inventory_hostname }}"

    - file:
        path: "{{ ospf_log_dir }}"
        state: directory

    - name: Verify quagga ospf loadbalancing
      test_ospf_loadbalancing:
        switch_name: "{{ inventory_hostname }}"
        config_file: "{{ lookup('file', '../../files/{{inventory_hostname}}/ospf_loadbalancing.conf') }}"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        package_name: "quagga"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ ospf_log_dir }}"
      register: module_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Fetch the log file
      slurp:
        src: "{{ module_out.log_file_path }}"
      register: logs

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ module_out.hash_dict }}"
        log_content: "{{ logs['content'] | b64decode }}"
      delegate_to: 127.0.0.1

    - name: Get goes version details
      shell: "goes hget platina package | grep version:"
      register: version_out

    - name: Get goes tag details
      shell: "goes hget platina package | grep tag:"
      register: tag_out

    - name: Store goes version and tag details in redis db
      store_goes_details:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        version_details: "{{ version_out.stdout }}"
        tag_details: "{{ tag_out.stdout }}"
      delegate_to: 127.0.0.1

    - name: Restore backup of /etc/quagga/ospfd.conf
      copy:
        src: "{{ quagga_ospf_conf_file_bck }}"
        dest: "{{ quagga_ospf_conf_file }}"
        remote_src: true
        owner: root
        group: root
        mode: 0644

    - name: Remove backup file
      file:
        path: "{{ quagga_ospf_conf_file_bck }}"
        state: absent

    - name: Restore backup of /etc/network/interfaces
      copy:
        src: /etc/network/interfaces.bck
        dest: /etc/network/interfaces
        remote_src: true
        owner: root
        group: root
        mode: 0644

    - name: Remove backup file
      file:
        path: /etc/network/interfaces.bck
        state: absent

    - name: Delete dummy interface
      command: "ip link del dummy0 type dummy"

    - command: "goes restart"


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"

#    - name: Get playbook run details
#      set_fact:
#        playbook_run: "{{ lookup('file', '{{ ansible_log_file_path }}') }}"
#
#    - name: Store the ansible execution log in redis hash
#      command: "redis-cli -p 9090 hset {{ hostvars['server_emulator']['hash_name'] }} 'result.playbook' '{{ playbook_run }}'"
#
#    - file:
#        path: "{{ ansible_log_file_path }}"
#        state: absent
