---

- hosts: server_emulator
  become: true

  tasks:
    - command: "date +%Y%m%d%T"
      register: start_time

    - set_fact:
        hash_name: "ipv4_configuration_interfaces_{{ start_time.stdout }}"
        start_time: "{{ start_time.stdout }}"


- hosts: leaf:spine
  become: true
  tasks:
    - name: Take backup of /etc/network/interfaces file
      copy:
        src: /etc/network/interfaces
        dest: /etc/network/interfaces.bck
        remote_src: true
        owner: root
        group: root
        mode: 0644


- hosts: leaf[0]:spine[0]
  become: true
  tasks:
    - name: Update eth-9-1 interface address
      lineinfile:
        path: /etc/network/interfaces
        regexp: "^  address 10.0.9"
        line: "  address {{ hostvars[inventory_hostname]['ipv4_config_ip'] }}"

    - name: Restart goes
      command: "goes restart"


- hosts: leaf[1]:spine[1]
  become: true
  tasks:
    - name: Update eth-5-1 interface address
      lineinfile:
        path: /etc/network/interfaces
        regexp: "^  address 10.0.5"
        line: "  address {{ hostvars[inventory_hostname]['ipv4_config_ip'] }}"

    - name: Restart goes
      command: "goes restart"


- hosts: leaf[0]:spine[0]
  become: true

  vars:
  - log_dir_path: /var/log/regression/ipv4

  tasks:
    - file:
        path: "{{ log_dir_path }}"
        state: directory

    - name: Verify ipv4 configuration interfaces
      test_ipv4_config_interfaces:
        switch_name: "{{ inventory_hostname }}"
        eth_port: "eth-9-1"
        spine_interface_list: "{{ groups['spine'] | map('extract', hostvars, ['ipv4_config_ip']) | join(',') }}"
        leaf_interface_list: "{{ groups['leaf'] | map('extract', hostvars, ['ipv4_config_ip']) | join(',') }}"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ log_dir_path }}"
      register: bgp_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ bgp_out.hash_dict }}"
      delegate_to: 127.0.0.1


- hosts: leaf[1]:spine[1]
  become: true

  vars:
  - log_dir_path: /var/log/regression/ipv4

  tasks:
    - file:
        path: "{{ log_dir_path }}"
        state: directory

    - name: Verify ipv4 configuration interfaces
      test_ipv4_config_interfaces:
        switch_name: "{{ inventory_hostname }}"
        eth_port: "eth-5-1"
        spine_interface_list: "{{ groups['spine'] | map('extract', hostvars, ['ipv4_config_ip']) | join(',') }}"
        leaf_interface_list: "{{ groups['leaf'] | map('extract', hostvars, ['ipv4_config_ip']) | join(',') }}"
        spine_list: "{{ groups['spine'] }}"
        leaf_list: "{{ groups['leaf'] }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        log_dir_path: "{{ log_dir_path }}"
      register: bgp_out

    - command: "date +%Y%m%d%T"
      register: end_time

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        start_time: "{{ hostvars['server_emulator']['start_time'] }}"
        end_time: "{{ end_time.stdout }}"
        hash_dict: "{{ bgp_out.hash_dict }}"
      delegate_to: 127.0.0.1


- hosts: leaf:spine
  become: true
  tasks:
    - name: Restore backup of /etc/network/interfaces 
      copy:
        src: /etc/network/interfaces.bck
        dest: /etc/network/interfaces
        remote_src: true
        owner: root
        group: root
        mode: 0644

    - name: Remove backup file
      file:
        path: /etc/network/interfaces.bck
        state: absent

    - shell: "goes hget platina package | grep version:"
      register: version_out

    - shell: "goes hget platina package | grep tag:"
      register: tag_out

    - name: Store GOES version and tag details in redis db
      store_goes_details:
        switch_name: "{{ inventory_hostname }}"
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
        version_details: "{{ version_out.stdout }}"
        tag_details: "{{ tag_out.stdout }}"
      delegate_to: 127.0.0.1


- hosts: server_emulator
  become: true
  tasks:
    - name: Get the test result from redis db
      get_test_result_from_redis:
        hash_name: "{{ hostvars['server_emulator']['hash_name'] }}"
      register: result

    - debug:
        msg: "Test case result: {{ result.result_status }}"

    - debug:
        msg: "Failure summary: {{ result.result_detail }}"
