---

- hosts: spine
  become: yes

  vars:
  - tmp_file_path: /tmp/failed.txt
  - log_dir_path: /var/log/regression/redis

  tasks:
    - file:
        path: "{{ tmp_file_path }}"
        state: touch
      delegate_to: 127.0.0.1
      changed_when: False

    - file:
        path: "{{ log_dir_path }}"
        state: directory

    - name: Test hset operations with invalid values on redis db locally
      test_redis_invalid:
        switch_name: "{{ inventory_hostname }}"
        log_dir_path: "{{ log_dir_path }}"
      register: invalid_out

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ invalid_out.hash_name }}"
        start_time: "{{ invalid_out.start_time }}"
        end_time: "{{ invalid_out.end_time }}"
        hash_dict: "{{ invalid_out.hash_dict }}"
        test_result: "{{ invalid_out.test_result }}"
      delegate_to: 127.0.0.1

    - lineinfile:
        path: "{{ tmp_file_path }}"
        line: "{{ invalid_out.hash_name }}"
      when: invalid_out.test_result == 'Failed'
      delegate_to: 127.0.0.1

    - name: Test hset operations with invalid values on redis db remotely
      test_redis_invalid:
        switch_name: "{{ inventory_hostname }}"
        switch_ip: "{{ ansible_ssh_host }}"
        remote_access: true
      delegate_to: 127.0.0.1
      register: invalid_out_remote

    - name: Store the test result in a hash in redis db on server emulator
      store_result_in_redis:
        hash_name: "{{ invalid_out_remote.hash_name }}"
        start_time: "{{ invalid_out_remote.start_time }}"
        end_time: "{{ invalid_out_remote.end_time }}"
        hash_dict: "{{ invalid_out_remote.hash_dict }}"
        test_result: "{{ invalid_out_remote.test_result }}"
      delegate_to: 127.0.0.1

    - lineinfile:
        path: "{{ tmp_file_path }}"
        line: "{{ invalid_out_remote.hash_name }}"
      when: invalid_out_remote.test_result == 'Failed'
      delegate_to: 127.0.0.1


- hosts: server_emulator
  become: yes

  vars:
  - tmp_file_path: /tmp/failed.txt

  tasks:
    - name: Report test suite result
      test_suite_result:
        result_data: "{{ lookup('file', '{{ tmp_file_path }}') }}"
      register: status

    - debug: var=status

    - file:
        path: "{{ tmp_file_path }}"
        state: absent
      changed_when: False
